### ISSUE TITLE
Not sure whats happening, might be IE

### ISSUE THREAD

**Issue by Drakoflame** [BluSunrize/ImmersiveEngineering#1009]
I'm not really sure WHICH mod is causing it, but when I glanced over the crash log, the thing that stands out to me was "Caught exception at Immersive Engineering" so, not sure where to go to, thought I'd bring it up here to see if someone could help me http://pastebin.com/e11FNWc7 there's the pastebin of the (what I think is needed) crash. I can easily re-create the crash by putting IE back in XD

If someone could let me know what to do to help fix this! :3

**Comment by malte0811** [comment]
I just looked at the code of ArchitectureCraft, the crash should be fixed in the latest or next version.

**Comment by Drakoflame** [comment]
Is that what was causing the crash? I also just checked an am apparently using an outdated version of Architecture craft. The way to get to the 1.7.10 download is complicated and not directly stated. I'm going to use the newest version and see if it still crashes then

**Comment by Drakoflame** [comment]
Alright, just did a test with the newest verion of AC, still crashed p np I think for now I'll take that one out because I like IE to much, especially the fact that I can make an assembly line and watch everything being made... https://www.youtube.com/watch?v=1oQnkHOa90k this song comes to mind every time I throw something onto the conveyor belts XD

**Comment by Drakoflame** [comment]
Don't know how, but I think the issue was solved? Apparently it was an ID conflict and for some reason IE was being flagged? Either way... works just fine now with Architecture Craft and IE
