### ISSUE TITLE
Constant & Consistent Crashing

### ISSUE THREAD

**Issue by grabvba** [BluSunrize/ImmersiveEngineering#1444]
As of yesterday I am no longer able to play for more than 5 minutes without a game crash. Looking through the log file it looks like it is IE related. 

I only seem to crash when my view is looking in the direction where most of our IE building has taken place. 

The only new IE item that we have built since the crashing has started is several Tesla Coils. Unfounded speculation, but perhaps a place to start.

IE -40
Forge 2076
MC 1.10,2

Server is currently ruining these mods, and have been since we started the seed

Advanced Inventory
BdLib
cxlibrary
Flight Simulator Mod (no objects have been built on the server from this mod recently.)

May be related to #1420

[crash-2016-09-13_08.44.49-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/468515/crash-2016-09-13_08.44.49-client.txt)

**Comment by theunkn0wn1** [comment]
... #1442... Amongst at least 3 others.

Known issue, has been fixed for an upcoming release.
Caused because TConstruct changed its API iirc

**Comment by grabvba** [comment]
Any idea what you're going to push that? Our server has become unplayable in the area around our IE items.

**Comment by theunkn0wn1** [comment]
From what i can tell this was fixed in commit 332c6b23cc68d5c20cec30a6eda6309c952734c3

As for when the fixed version is released i cannot speak for @BluSunrize, the mod developer, though i would expect a release soon given how many people have reported this issue (8 related issue threads and counting!) Sorry :/

**Comment by BluSunrize** [comment]
Just disable TCon compat in the config. Should have you safe until the new version releases.
Also, search before you open new issues.

**Comment by grabvba** [comment]
Disabling TCon does not fix the crashing, same crash same type. 

Building a new mod with the last commits however does fix the crash.

**Comment by BluSunrize** [comment]
I said disabling TCon compat. In the IE config. Needs to be done on servers and clients. If that still crashes, please pastebin the logs.

**Comment by grabvba** [comment]
Sorry for taking a while to respond, haven't had a chance to play or test. 

This is the crash log from a crash after disabling TCon compat. We built the commit that fixed it and that worked fine so it's a bit moot at this point but, here it is, for science. 

[crash-2016-09-13_21.06.37-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/475881/crash-2016-09-13_21.06.37-client.txt)

**Comment by Joshwoo70** [comment]
Why are you building from source?

**Comment by theunkn0wn1** [comment]
Because he needed the fix urgently, and didn't want or was otherwise unable to wait for the official release.

**Comment by BluSunrize** [comment]
The crash is also unrelated, once again the stupid Forge bug strikes that makes TESRs render where their blockstate isn't found.

**Comment by grabvba** [comment]
Josh, because the game was unplayable with IE installed for all of my users and building the mod and distributing was easier than explaining how to edit everyone's configs.
