### ISSUE TITLE
1.10.2 Creosote & Railcraft 10

### ISSUE THREAD

**Issue by RiverC** [BluSunrize/ImmersiveEngineering#1659]
1. When railcraft 10.0.0 and IE are installed and railcraft compat is enabled, creosote appears as an untextured fluid, and you cannot pull creosote out of the coke oven.

2. As 1. but compat disabled is the same. 

3. With just railcraft, creosote has proper texture.

4. With just IE, creosote has proper IE texture and you can remove creosote from the coke oven.

I expect that with railcraft compat disabled, I should have two different creosote fluids and two different creosote buckets, which I could then use crafttweaker to create a conversion recipe between as needed. However, disabling compat doesn't seem to help with this fluids issue, it looks like the coke oven still tries to produce railcraft's creosote, which then cannot be turned into the only registered creosote bucket, which is then railcraft's. In that case, IE's creosote bucket ceases to be available (or something of this sort; JEI obviously has limitations.)

Any help with this issue?

**Comment by BluSunrize** [comment]
they /should/ be the same fluid. That's the entire point of the fluid registry. If they have the same ID, they are supposed to be the same. I keep getting reports of Creosote incompatibilities with Railcraft and to my knowledge, I shouldn't be at fault.
But since this issue keeps popping up, I'll have a dig in Railcraft's code to see if it's my fault at all.

**Comment by malte0811** [comment]
I think this was fixed on RC's side, I saw a commit closing CovertJaguar/Railcraft#934.

**Comment by RiverC** [comment]
Sorry to make it an issue for you if it isn't. I thought turning off Railcraft compatibility would separate the mods' creosote, but as I haven't coded MC since the end of alpha, forge and the fluids registry is foreign to me.

**Comment by zepanv** [comment]
This is still an issue as of IE-0.10-48 and Railcraft-1.10.2-10.0.0

**Comment by mindforger** [comment]
@zepanv that is not the exact _latest_ version of Railcraft, CovertJaguar mentioned it would be fixed in RC-10.0.0-beta4 or later but it is not yet available on the webpage, you may look at his jenkins build server if you are able to find it XD cause i didn't

**Comment by zepanv** [comment]
@mindforger I believe b4 is older, according to the dev access I have 10.0.0-beta-4 has a date of oct 22, and 10.0.0 is oct 31.

**Comment by mindforger** [comment]
sounds a bit strange to not upcount the version when leaving beta, but if that is so i have said nothing, sorry then

the other issue 
https://github.com/CovertJaguar/Railcraft/issues/1012
hasn't yet been solved either

**Comment by Vaygrim** [comment]
This is, unfortunately, still an issue when using the latest versions of IE and Railcraft available from Curse.
