### ISSUE TITLE
Rendering Glitch - Coke Oven and Blast Furnace

### ISSUE THREAD

**Issue by Ra-Zim** [BluSunrize/ImmersiveEngineering#1941]
So, for some reason when right clicking on the center block for the Coke Oven and Blast Furnace, more pieces appear. They are not actually there, but they look very strange.

Edit: When breaking any blocks on either of them, additional blocks are created and fly off from the main structure. Causing duplication.

Forge Version: 1.10.2-12.18.3.2221
Immersive Engineering Version: 1.10.2-0.10-57

(I put a wood block in there to show that the blocks are phantom)
![2017-03-06_17 47 08](https://cloud.githubusercontent.com/assets/11083387/23636820/f368f844-0294-11e7-923a-b9f252ea59b2.png)

![2017-03-06_17 37 07](https://cloud.githubusercontent.com/assets/11083387/23636785/b3acf37c-0294-11e7-9400-7bde63c52c2a.png)

**Comment by BluSunrize** [comment]
Is this singleplayer or on a server?

**Comment by malte0811** [comment]
And if it is a server, is it just Forge or something like Cauldron/Thermos/Spongeforge? I seem to remember such issues happening with non-normal-Forge servers.

**Comment by Ra-Zim** [comment]
It is not happening on single player, so it is only a server and we are running with Spongeforge

**Comment by i9hdkill** [comment]
We have that problem aswell:
SpongeForge 2219
ImmersiveEngineering: 0.10-57
Forge: 1.10.2-12.18.3.2254
When rightclicking with the hammer it sometimes glitches out like this:
http://prntscr.com/eimzwq

**Comment by BluSunrize** [comment]
I honestly wish I knew how and why Sponge causes this, but alas, I have no fracking clue...

**Comment by i9hdkill** [comment]
Wanna point to the partof the code, that tranforms the blocks into the oven while rightclicking? I can pass that to a sponge dev. Guess that is related to forge/sponge phases, where the mod places stuff without forge/sponge knowing about it or similiar.

**Comment by gabizou** [comment]
> I honestly wish I knew how and why Sponge causes this, but alas, I have no fracking clue...

It's still a mystery to me as well... When I get a chance to investigate it, I'll be investigating it.

**Comment by KaneHart** [comment]
@gabizou 
Not sure if this will help but we have actually had even bigger errors with it:
https://pastebin.com/Yfy0eiV3

Someone was trying to assemble  it and did not work so they broke it and was causing those errors and did not get all the blocks back. Playing a Hardcore (Expert) Pack these guys are suffering a lot with having to refarm for mats.

**Comment by benknight04861** [comment]
In case it helps anyone figure out the problem I found that placing an empty bucket in the Coke Oven to remove some of the creosote oil seems to immediately fix the visual duplication of the Coke Oven.  I've not found a similar easy fix for the Garden Cloche or Water Wheel. (I.E. 0.11-63)

**Comment by KasperFranz** [comment]
@benknight04861 I am quite sure it is fixed in sponge since issue https://github.com/SpongePowered/SpongeForge/issues/1343 is closed now :)

**Comment by benknight04861** [comment]
Sorry I think I'm actually seeing a different visual issue.  Will try to find a better ticket or make a new one.

**Comment by ALoveOverall** [comment]
This still exists in 1.12 using 0.12-70
![2017-08-08_12 22 39](https://user-images.githubusercontent.com/30839490/29082965-29c082bc-7c35-11e7-80e4-6b9f1e4bb74d.png)

Found my bank of Coke furnaces looking like this after updating from 1.11

**Comment by ALoveOverall** [comment]
This still exists in 1.12

IE Ver: 0.12-70
Forge Ver: 1.12-14.21.1.2443

![2017-08-08_12 22 39](https://user-images.githubusercontent.com/30839490/29084471-0a78d256-7c3a-11e7-9099-bb640a7bbad0.png)

New furnaces render and work normally; However, all furnaces updated from 1.11 render as pictured above and interacting with them in any way causes a crash.

**Comment by BluSunrize** [comment]
1.11 to 12 isn't necessarily fully compatible. Just fill with air and refund materials.
