### ISSUE TITLE
bad Arc furnace collision

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#270]
same gist as #262 but that one was closed and fixed.
![image](https://cloud.githubusercontent.com/assets/3110986/9075311/5e018b08-3ac8-11e5-9cc5-b39cc7fb6881.png)
![image](https://cloud.githubusercontent.com/assets/3110986/9075318/6e87c500-3ac8-11e5-8d22-80b55a2e247f.png)
----------------------------
![image](https://cloud.githubusercontent.com/assets/3110986/9075354/b5b469f6-3ac8-11e5-8657-2229a645dc92.png)

a fix would be to add extra collision boundaries (or whatever you call them) where the redstone blocks(for clarity) are.

============================
IE build 0.5.0 3bc2e46b5515b958c8ed53134faf715ee545431f

**Comment by BluSunrize** [comment]
You're kidding, right? The fact that #262 was fixed and closed kinda implies that this was FIXED. You do not need to report it anymore. Go download IE 5.1, and create the structure. it now needs two extra steel blocks.

**Comment by theunkn0wn1** [comment]
No its not fixed, i just pulled at exactly 9:50 PST the latest build available on github, 0.5.1 SHA 4074c1d586ec31809ca18349acc68eb2e0ac216a,
 and this problem *still exists*
![image](https://cloud.githubusercontent.com/assets/3110986/9091963/22900064-3b58-11e5-8bdc-7ecf0248ec9e.png)
![image](https://cloud.githubusercontent.com/assets/3110986/9091971/3080e21a-3b58-11e5-93c6-8f3da1df2e1a.png)
![image](https://cloud.githubusercontent.com/assets/3110986/9091981/3fbe43e4-3b58-11e5-8cdc-fbf2692f3973.png)
I rebuilt the arc-furnace BTW, after updating to 0.5.1
--------------
the **only** reason i reported this was the problem persisted *after* you issued the fix for #262 and i build IE off that commit. I am not an idiot out for kicks by wasting both your time and mine just because i felt like it. I am aware of #262, and the fact that the issue described there does not appear to be resolved, that is the **only** reason i created a new issue thread.

what exactly am i missing?
The "extra two steel blocks" you reffer to? where do they go as the structure still forms the old way, and the book still displays them the old way.
if it is not clear by now, i am currently using IE version 0.5.1 SHA 4074c1d586ec31809ca18349acc68eb2e0ac216a
----------------------

**Comment by BluSunrize** [comment]
Okay, this is indeed my bad. This was caused by me doing debug stuff and resetting the structure to its original, broken version whenever it was requested by the book. Mea Culpa. That you for the continued pointing out of my flaw, I'll fix it for the next one.
