### ISSUE TITLE
[1.12] Wires Disconnect from Transformers

### ISSUE THREAD

**Issue by SaintWacko** [BluSunrize/ImmersiveEngineering#3025]
### Description of the issue:
When the chunk containing my transformer loads, the Insulated MV Wire connecting my MV Capacitor to the Transformer pops off and drops as an item. This is occurring in single player, I have not tested it in multiplayer.
[Screenshot of the wire in question](https://i.imgur.com/ZxESuR3.png)
Related:
https://github.com/DarkPacks/SevTech-Ages/issues/2469
https://www.reddit.com/r/feedthebeast/comments/8nsd6e/why_does_this_wire_keep_breaking/

### Versions & Modlist
[Sevtech: Ages 3.07](https://minecraft.curseforge.com/projects/sevtech-ages)
Optifine 1.12.2_HD_U_D1
Environmental Creepers 1.12.2-1.4.0
Cosmetic Armor Reworked 1.12.2-v1
Chunk-Pregenerator V1.12-1.8
Immersive Engineering 0.12.82
forge 14.23.3.2679

**Comment by SirDavidLudwig** [comment]
This issue actually seems to apply to any connector type in the latest commit. If the power signal is change in a connector that is in an unloaded chunk, it causes the wire to get dropped.

**Comment by SirDavidLudwig** [comment]
Further inspection, it was a result from the commit b61b51d4bbb90cffe8a60eaa7bcd1d17a5c111f9

**Comment by malte0811** [comment]
The above commit should fix this, at least as far as I could reproduce it.
@SaintWacko could you test with [this](https://ci.blamejared.com/job/Immersive%20Engineering/401/) build of IE? I'm not sure whether I fixed your case, I know I fixed @SirDavidLudwig's. If the wires still disconnect with that build it would be great if you could upload your world and post a link here. If that's too big, remove all region files except the one indicated by [this tool](https://dinnerbone.com/minecraft/tools/coordinates/) from the upload (but not from the version of the world you use!).

**Comment by SirDavidLudwig** [comment]
Haha, I love how fast you fixed that. I've been trying to figure out how to fix this myself for like a week now...

**Comment by SaintWacko** [comment]
@malte0811 Nope, didn't fix it for me. Here's a copy of my world with all the dimensions and regions removed except the pertinent ones: https://drive.google.com/open?id=1RDJsu0yDISaUXu3B0vBMU-LsfsShq5Ny

I can reliably reproduce the issue by flying a couple hundred blocks south (far enough to unload the chunk), saving and exiting, reloading the world, and returning to my base, at which point the wire has popped loose.
