### ISSUE TITLE
Silent Crash (Stall) with Fluiducts from TE and PlantOil

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#35]
i allowed myself to compile from your github to test this mod for myself a bit and got a complete hang-up of the server when running Thermal Dynamics Fluiducts 

it looks like the fluid is causing some trouble to the oredict somehow, ending in some sort of deadloop.

the server is not responding to anything anymore not even commands in the command line.

Stack Trace
Server thread [39] (RUNNABLE)
   java.util.HashMap$HashIterator.<init> line: not available 
   java.util.HashMap$KeyIterator.<init> line: not available 
   java.util.HashMap$KeyIterator.<init> line: not available 
   java.util.HashMap.newKeyIterator line: not available 
   java.util.HashMap$KeySet.iterator line: not available 
   java.util.HashSet.iterator line: not available 
   java.util.AbstractCollection.toArray line: not available 
   net.minecraftforge.oredict.OreDictionary.getOreIDs line: 328 (sometimes 326)
   blusunrize.immersiveengineering.api.ApiUtils.compareToOreName line: 14 
   blusunrize.immersiveengineering.api.DieselHandler.getPlantoilOutput line: 66 
   blusunrize.immersiveengineering.common.blocks.metal.TileEntitySqueezer.func_145845_h line: 83 
   net.minecraft.world.World.func_72939_s line: 1939 
   net.minecraft.world.WorldServer.func_72939_s line: 489 
   net.minecraft.server.MinecraftServer.func_71190_q line: 636 
   net.minecraft.server.dedicated.DedicatedServer.func_71190_q line: 334 
   net.minecraft.server.MinecraftServer.func_71217_p line: 547 
   net.minecraft.server.MinecraftServer.run line: 427 
   net.minecraft.server.MinecraftServer$2.run line: 685

**Comment by mindforger** [comment]
i should add, that the multiblock was formes properly, some regular seed has been placed into it and it was all powered up, when placing the fluiduct the server hung up

**Comment by mindforger** [comment]
meh nevermind, i've found it!

in line 83-85 in your squeezer is a broken if statement :P i try to use the one from the fermeter code and test it

**Comment by DoughnutDev** [comment]
If you compiled this from GitHub sense that is out of date and suspended.
It is most likely fixed in private builds of the mod. Which I think it is
fixed already.

**Comment by BluSunrize** [comment]
The Squeezer and Fermenter have seen a lot of revisions since the last push here, so I'm not gonna bother with this one

**Comment by mindforger** [comment]
hm okay, it did not fix the issue
 so still present

i thought it might help but i did not recognize it's suspended ... how unfortunate :( its fun to play with it already XD it just needs some "inserter robot arms" to look like factorio XD
