### ISSUE TITLE
Wire fry/render issue

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#428]
Issue: Mv wires, when fried, do not always destroy/invalidate the connections.

When using Mv wires to draw off the power generated from a diesel generator, **intentionally**, I found a case where the wires do not properly fry from overload.

Possible steps below:
[1] Build diesel generator correctly
[2] place three Mv Wire connectors to the OUTPUT faces of the generator.
[3] wire all three together in series
[4] wire one of these connectors to a RF consumer. (in my instance a Trash Can)
[5] replace fried cable starting from consumer to provider (order specific!)

I am having dificulty understanding what exactly i have done, will be more clear [here](https://youtu.be/hBqWUtv-QN0) in a youtube video

.. IE Version 0.6.0_pre SHA 2fec12bbd2ec1a4981de46236e278bc4124c2857

**Comment by mindforger** [comment]
i did not dig into the code yet but i want to tell here, that this MAY be an glitch issuewith asynchronous update of the connectionslist, was this on a server or on single player?

**Comment by malte0811** [comment]
A few notes on this: i am working on a pr in that general area(hashcode, equals and compareto in connection), but have no idea on that specific problem. When testing burning wires with the current master version, make sure that the nether is not loaded, otherwise it won't work at all(i have a fix for that commited, but not pushed yet). In some situations it seems like there are multiple connections between the same points, debug output shows a different (acording to hashcode) connection getting burned each tick and new flames keep apearing every tick, but not indefinitly. The branch i am working on is indirectConnections, i will push the fix i mentioned later today.

**Comment by mindforger** [comment]
@malte0811 in the past recommended using concurrentMaps and concurrentLists because of several other mods hooking into the system causing concurrent modification exceptions, keep that issue in mind while working on those ConnectionLists!

one major side effect of those maps is, their created iterators keep the original order and also keep weak links to the items, even if those items were removed from the list while iterating over an existing iterator! This can lead to temporary ghost connections either visually or programatically

what you observed may be an hint:
a cable beeing removed in some odd order because of burning away, while another power transfer is going on, but using an "outdated" iterator, repeatedly causing another burn of the ghost cable! Maybe ther is an additional existence check missing?!

but the major win is, it won't fail and crash if the list is modified in some undesigned order

**Comment by theunkn0wn1** [comment]
Single player

**Comment by BluSunrize** [comment]
Should be fixed now

**Comment by theunkn0wn1** [comment]
Not fixed. Still able to reproduce with 641c7430f1417b9026e0b74ba5f3f5dcb67a870e.
Setup shown below.
![image](https://cloud.githubusercontent.com/assets/3110986/9983986/a2b2ed1c-5fc3-11e5-9aa1-acbf9ab20db3.png)

**Comment by cobra** [comment]
I've seen these problems as well during testing, esp. for #385.
I've added some debug logging now. I see the connections getting burnt (by EventHandler.java) and removed (ImmersiveNetHandler.java), but they stay visible and I can't rewire them. Logging out and back in doesn't help. Most of the time I'm wiring 3 segments between 2 HV connectors and 2 Relays and at least one, most of the time two, connections don't get deleted properly, sometimes all 3 aren't deleted. They are visible, I can't rewire between these connectors, but they aren't conducting RF and I need to use the wire cutter and rewire. I'm examining this further.

**Comment by theunkn0wn1** [comment]
I cannot reopen this as @BluSunrize closed it.... given this issue is still
occurring can Blu reopen this issue?

**Comment by malte0811** [comment]
Ok, i have a potential fix, the client was re-adding the connection when receiving the update packet. Please test [this](https://github.com/malte0811/ImmersiveEngineering/tree/burningWires) version and tell me whether the bug is fixed.

**Comment by theunkn0wn1** [comment]
question... why is your lib using version 0.5.4? 
built to your branch as linked above, SHA 94d13c1e59889349aaf00d2c389b8a58ba5a9ec5, and this completley breaks wire fry.

Same setup as above, and the wires do not fry at all.

**Comment by malte0811** [comment]
Where am i using version 0.5.4? The build.gradle says it is for version 0.6-pre. Also it did not break anything in my test enviroment, but i used a different test case: 2 creative energy cells, both have 2 connections to cryo-fluxducts that are wired together, one cell is set to input and one to output. It fried the wire correctly in both singleplayer and on a dedicated server.

**Comment by cobra** [comment]
I've seen these additional `addConnection` calls yesterday evening and just wanted to continue looking into this.
@malte0811's change seems to fix this for me (looks fine and works fine, no method calls which shouldn't exist, at least not for those where I added logging), but I don't quite understand why we need this distinction between SP and MP when we're already checking where this code is running.  Can you explain that? Also, How the heck did you find this?

@theunkn0wn1 works fine for me. I don't understand what you are saying.

**Comment by theunkn0wn1** [comment]
Wierd... i did a fresh Git pull from https://github.com/malte0811/ImmersiveEngineering/tree/burningWires
SHA 94d13c1e59889349aaf00d2c389b8a58ba5a9ec5
and the Build.gradle has `version = "0.5.4"
Did i pull from the wrong branch?

**Comment by cobra** [comment]
@theunkn0wn1 what was your way of pulling? GUI, command line? Can you paste the command? Looking at the repo, it's 0.6-pre:  https://github.com/malte0811/ImmersiveEngineering/blob/burningWires/build.gradle#L20

**Comment by malte0811** [comment]
@cobra i did not look into the reasons too much, but i think that the update packet was send before the wire was fried, but received afterwards. The difference is that in sp the server uses exactly the same nethandler instance as the client, therefore the wire gets added on both the server and the client "side". But in that case it is not even necessary to react to data packages, as the changes are there already.

**Comment by theunkn0wn1** [comment]
Browsed to the mentioned branch in my browser (Chrome) and clicked the "clone to desktop" which launched the Git GUI. Once obtained i used the Git shell to execute a `git pull` which returns `already up-to-date.` 
 it appears that that process went wrong. It cloned the 'master' branch....

**Comment by cobra** [comment]
so it's packet chaos once again -.- BTW: is there some way of debugging the packet handling somewhat conveniently to discover (and diagnose without guessing) something like this?

I still need to investigate some weirdness when adding wires *without* forming a complete connection between a RF source and sink, unrelated to this frying/burning issue. My logging showed rather insane amounts of connections getting added, sometimes with the wrong cableType as well (e.g. steel, steel, electrum, steel). This happened on the master branch.

**Comment by cobra** [comment]
@theunkn0wn1 you can clone and checkout a branch other than master by adding --branch <name> to the clone command. [I've already added @malte0811's repo as a remote to my local one. Very convenient for these feature branches.]

BTT: I didn't see any broken `addConnection` call with this server check in place. Looks like that cableType weirdness had the same cause.

**Comment by theunkn0wn1** [comment]
@cobra I fixed it my end, the cloning proccess via the website ignores branches, or so it seems.
I managed to retrieve the correct branch manually via the commandline. via 
`git clone -b burningWires https://github.com/malte0811/ImmersiveEngineering.git`

Anyways, you guys know way more than I when it comes to this kinda stuff, i will leave the debugging to you two.

**Comment by cobra** [comment]
I've got some ghost connections in my test world which get included in the packets, but don't exist at all. There aren't even connectors at the other end point (I destroyed them many launches ago). They don't cause wrong `addConnection` calls any more like they did before this server check. I don't know how they didn't get deleted properly.

Should we include some form of sanity checks against problems like this or do we ignore it as debugging glitch? I'll keep the "broken" world with these connections untouched in case we need it for further testing.

**Comment by mindforger** [comment]
maybe add a config option which resets itself when enabled so it only runs once:
the function is, on loading the network, the correlation of a node inside the network is checked againts a valid existing world object and get's removed if there is no object for this node

just like thaumcraft is resetting the stored essentia tables in the world when told by config

**Comment by BluSunrize** [comment]
What a config to just remove all wires once?

**Comment by mindforger** [comment]
it should only remove ghost connections like @cobra described that are not related to any actual ingame connectable!

**Comment by cobra** [comment]
I've added a simple connection validator which ensures that every connection being loaded has a valid endpoint when starting a server and loading the world save data. It clears these ghost connections I mentioned above successfully and forever.
At the moment it's config option set to off by default and won't do any further validation like checking whether the wire can actually connect (wire type, number, etc) or line of sight. It will load all endpoints of all connections for this and ignore whether chunks are loaded or not, so it will probably slow down the server start when a world has a large amount of connections in a lot of chunks.
I've pushed this rather simple version to https://github.com/cobra/ImmersiveEngineering/commit/1244112279827661e2b96757e32dfc85b991d169

**Comment by cobra** [comment]
@BluSunrize what do you think about this validation idea? Should I PR it? Or add something? It could be extended to other save data as well.

**Comment by BluSunrize** [comment]
By all means, go ahead. ^^

**Comment by theunkn0wn1** [comment]
Sorry for resurrecting a corpse, but the beast still lives on..
So @malte0811 your commit seems to have fixed most instances of this glitch though not all :/ 

I have a setup that involves over four max-length HV cables running from a source to a consumer. If i overload the line between the two points not all cables are cleaned up. In fact, it only melts the cable segments that are within one 'hop', or relay, of the source of the overload.

If i intentionally introduce a fault at the source end, such as crossing two separate HV output lines, and if the consumer can accept it, the wires within two chunks of the fault melt whilst the others that are closest to the consumer become orphaned. The orphaned cables do not function (good) and are properly cleaned up upon reboot but still render visually till then. 

yeah it gets cleaned up upon reboot (thanks @cobra ) but the issue itself lives on.

IE built against d62c1aa3c81aac527fe45df8fbb5ab19b9387e84

**Comment by cobra** [comment]
Wait, you're not breaking connectors or relays, do you? Then it's not my validator that's cleaning up this mess. As long as the start and end points exist, the connection gets added.

**Comment by theunkn0wn1** [comment]
Your code is what is cleaning up the glitch on restart, last i checked(#471?)
Breaking the connectors does seem to cleanup the glitch as well.
However, if the connectors and/or relays remain untouched a reboot is required to clean up the should be melted cables.

**Comment by malte0811** [comment]
Are we talking about a dedicated or an integrated server here?

**Comment by theunkn0wn1** [comment]
Integrated, In my Singleplayer test worlds

**Comment by cobra** [comment]
Smells like a sync issue to me. (no, I'm not debugging this now. I'm currently working on the excavator sync stuff)

**Comment by malte0811** [comment]
I will look into this. Just a short question, @cobra: those connections with one non-IIC connector your code removes on startup: did they render, even after a mc-restart?

**Comment by cobra** [comment]
The ones I had did not, they formed a completely separate "ghost net" with nothing triggering the wire render for them. Their endpoints were mostly air.

**Comment by malte0811** [comment]
I have found the problem, a fix will probably require more experience with the MC rendering code than I have. Minecraft is apparently caching the tile render results and keeps rendering those once the squared distance to the player is more than `TileEntity.getMaxRenderDistanceSquared()`. Overriding this method in `TileEntityImmersiveConnectable` and returning `Double.MAX_VALUE` fixes it, but it isn't a sollution that should be used for a release.
