### ISSUE TITLE
Potential problems with Minetweaker added Minerals

### ISSUE THREAD

**Issue by 1skandar** [BluSunrize/ImmersiveEngineering#730]
First problem if you put a space in the name of a mineral it is unusable. Ore Rich Stone will not work, but OrerichStone will. This, at least, fails with the /ie mineral set in game.Possibly intentional, but if so it would be nice to have that documented.

Second, and this one is harder to prove, it looks like Minetweaker added minerals don't generate naturally _at all_ and, in fact, interfere with normal generation. Ran roughly 100 chunks through the core sample, got 6 hits and _none_ were my custom minerals. This is a rate of 1 in 16 or 1 in 17 chunks per mineral. (oh, and this was _after_ I discovered the above problem and removed all the spaces in the names). Removed all the custom work, ran an additional 40 chunks with just the default mineral set and got 7 hits, close enough to bang on the 1 in 6 it should be.  Again, it is _really_ hard to prove a negative and what I got may have been a statistical anomaly, but this seems to be a problem.

**Comment by 1skandar** [comment]
Edit: Ran through another 50 chunks and finally found one of my custom veins. That said, 150 chunks and only 9 hits and only 1 of those being my custom veins seems to confirm there is something wonky going on.

**Comment by BluSunrize** [comment]
Well it all depends on what weight you gave the vein. Weight determines how frequent you'll find it.

**Comment by 1skandar** [comment]
Yeah, that is part of the problem. The total weight of the custom stuff should be roughly 1/3 to 2/5 of the total weight of everything, which means out of the 9 I got I should have hit 3 ish.

And even outside of that, the overall rarity of the minerals seems to rise dramatically with custom veins enabled. Again, 150 chunks and only 9 hits of ANY mineral veins custom or otherwise, or roughly 1 in 17. Again, that *might* be a statistical anomaly, but that certainly seems off when I should have hit two to three times that many.  and, in fact, when I'm running just defaults without any custom veins I pretty much do hit the 1 in 6 that is expected.

Something is funky. I'm not sure what, but something is decidedly off. I'd like it if you could take a look yourself. I ran through 200 chunks yesterday placing core drills and getting samples and even with the speed of those things turned up high it was a chore and a half.

**Comment by cobra** [comment]
You can use `/ie mineral get` instead of the drill for testing purposes, that is way faster.

**Comment by 1skandar** [comment]
Oh, well THAT will speed further testing. Off to go gather more data.

**Comment by 1skandar** [comment]
Ok, this is frustrating. 400 chunks later and my data is just inconclusive. 200 non-custom chunks tested, 31 hits. Not quite 1 in 6 but very, very close.

200 chunks with custom veins added 25 hits. 1 in 8, which *is* low, but not as low as what I found last night. 

I'm not sure what to make of this. A grand total of 350 chunks ran across 3 worlds and 34 total hits, or about 1 in 10. 240 chunks with the default mix and 38 hits, or just about the 1 in 6 as expected. From a statistical point of view there might be something there....or maybe I just had bad luck with a world or two.

Ah well, I'm just going to leave this here. I'm not sure how you'd reliably test this, or even what could possibly be wrong

For completeness sake, here are my added mineral veins, via Minetweaker:

* mods.immersiveengineering.Excavator.addMineral("Tungsten", 20, 66, ["oreTungsten", "oreSalt"], [98, 2], [0], false);
* mods.immersiveengineering.Excavator.addMineral("Emery", 10, 35, ["limestone", "oreEmery"], [88, 12], [0], false);
* mods.immersiveengineering.Excavator.addMineral("OreRich", 35, 20, ["oreCopper", "oreTin", * "oreCheese", "oreMeteoricIron"], [45, 45, 4, 1], [-28], false);
* mods.immersiveengineering.Excavator.addMineral("OreRich", 35, 20, ["oreIron", "oreCopper", "oreTin", "oreDesh", "oreMeteoricIron"], [30, 30, 30, 5, 5], [-29], false);
* mods.immersiveengineering.Excavator.addMineral("ElementalInfused", 10, 50, ["oreShardElemental", "oreShardFire", "oreShardWater", "oreShardEarth", "oreShardAir"], [60, 10, 10, 10, 10], [0], false);
* mods.immersiveengineering.Excavator.addMineral("Tritanium", 30, 10, ["oreTritanium", "oreDilithium"], [99, 1], [0], false);
* mods.immersiveengineering.Excavator.addMineral("GemMotherlode", 5, 75, ["oreChaos", "oreRuby", "oreGarnet", "oreTopaz", "oreHeliodor", "orePeridot", "oreBeryl", "oreAquamarine", "oreSapphire", "oreIolite", "oreAmethyst", "oreMorganite", "oreOnyx"], [76, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [0], false);
* mods.immersiveengineering.Excavator.addMineral("FusionIsotopes", 20, 35, ["oreBoron", "oreLithium"], [50, 50], [0], false);
* mods.immersiveengineering.Excavator.addMineral("RadioactiveOres", 20, 35, ["oreUranium", "oreThorium", "orePlutonium"], [65, 30, 5], [0], false);

**Comment by BluSunrize** [comment]
^ that commit adds an additional clearance to the total weight calculations. If you can compile a build yourself @1skandar, maybe try if that helps?

**Comment by 1skandar** [comment]
Um, I know *how*, yes, but I don't currently have a workspace set up. I will give it a shot and report back.

**Comment by 1skandar** [comment]
No luck. It's been a while (like 1.4.7) since I last setup a workspace and gradle is giving me a headache.

**Comment by BluSunrize** [comment]
Don't worry yourself about it then, I'll probably build+release today. If the issue persists, we'll have to work on it for future versions.

**Comment by 1skandar** [comment]
I tested the new version. 1 in 12.5 out of 100 chunks tested. Not statistically significant yet. I'd like to run another couple of hundred chunks to say whether this is an outlier or not. Regardless, this is beyond frustrating. I can certainly point at it and say "This looks wrong" but I can't pin down a why.

**Comment by Blue64** [comment]
Items may contain spaces in MineTweaker, this was resolved long ago, it's handled via something to deal with the brackets and the tokener, I'm not quite comprehending the specifics, but it works for items. ___Fluids are another story.___

Speaking of MineTweaker, I went from IE doing an invalid call in the newest ```Forestry 4.2.2.860``` (4 IE releases ago) to IE conflicting with ```MineTweaker``` for the current IE release.

**Comment by BluSunrize** [comment]
@Blue64 you missed the issue. Minetweaker works fine, ingame commands don't.
I might have to adopt that bracket thing for them.

**Comment by BluSunrize** [comment]
there we go @1skandar, I added a new thing to commands where you can use <> to bracket in a string with spaces, so that should make veins like <Very Cobbly Copper Vein> possible to use with commands =3
To be released with IE 0.7 due today or tomorrow.

**Comment by 1skandar** [comment]
Thank you kindly.

**Comment by Blue64** [comment]
Glad I could help ```:)```
