### ISSUE TITLE
No Energy Transfer with newest Version (0.6.3)

### ISSUE THREAD

**Issue by aikpoppel** [BluSunrize/ImmersiveEngineering#743]
Hey Blu,

have have now tested 1 hour and every generator, connector, cable, capacitor and no energy transfer and generation is possible with the new version, dont now i have miss something...
LG Aik

**Comment by Pihrra** [comment]
I'm having the same issue. I tried replacing wires, capacitors, connectors, just updating the blocks, changing the power outputs, nothing works. For example one of my capacitors that starts a chain of powered lamps is full but none of the lamps are turning on. I did manage to power a charging station directly next to a capacitor however.

**Comment by malte0811** [comment]
I asume you both either have no ic2 or have integration disabled?
@BluSunrize [this](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityConnectorLV.java#L84) looks broken...

**Comment by Pihrra** [comment]
Indeed I don't have IC2 installed

**Comment by cosmicdan** [comment]
Just to add, I have IC2 and the upgrade went fine - no such problem here.

Well, unrelated (but just an FYI) I did have a crash - dump below - but this was resolved by updating to the latest IC2 build (or maybe it was just a coincidence). Also two specific LV wires decided to disappear, but that's no big deal.

```
java.lang.NullPointerException: Ticking block entity
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.transferEnergy(TileEntityConnectorLV.java:288)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.func_145845_h(TileEntityConnectorLV.java:57)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by 1skandar** [comment]
I can attest to this. No IC2 and no power transfer.

**Comment by BluSunrize** [comment]
Oh for Petes sake >=/
Well,  guess I'm releasing 0.6.4 later today >_>

**Comment by cobra** [comment]
fixed.

**Comment by xanderc2** [comment]
Still not working to me, i tryined everything, everymod updated to latest version, still not transfering energy D:

**Comment by cobra** [comment]
0.6.4 HAS NOT BEEN RELEASED YET, IT CAN'T WORK

**Comment by BluSunrize** [comment]
^ what he said >_<

**Comment by xanderc2** [comment]
I downloaded 0.6.3 relased 40 hours ago on curse, i realized it were the latest one, sorry :D
