### ISSUE TITLE
Crushing most ores with the Engineer's Hammer yields multiple copper ingots

### ISSUE THREAD

**Issue by vitraiden** [BluSunrize/ImmersiveEngineering#766]
In IE 0.6.4, when combining the Engineer's Hammer with gold ore or any of the non-vanilla ores used by IE then the crafted result is a small stack of copper ingots rather than the appropriate grit.  The problem does not manifest in the case of iron ore nor when using the Crusher multiblock.  See screenshots below.

I am using:
Forge 10.13.4.1541
CraftGuide 1.6.8.2
DrCyano's Lootable Bodies 1.3.6

![2015-12-11_18 31 47](https://cloud.githubusercontent.com/assets/10928371/11758833/bb249190-a035-11e5-9ee8-71dd2fcd336f.png)
![2015-12-11_18 31 04](https://cloud.githubusercontent.com/assets/10928371/11758835/bb275d30-a035-11e5-91e4-a38b8cc6e3e2.png)
![2015-12-11_18 31 17](https://cloud.githubusercontent.com/assets/10928371/11758836/bb289632-a035-11e5-9858-5b5c47678c8c.png)
![2015-12-11_18 31 29](https://cloud.githubusercontent.com/assets/10928371/11758834/bb25b99e-a035-11e5-9ad9-ecdd8c3b49cc.png)
![2015-12-11_18 40 10](https://cloud.githubusercontent.com/assets/10928371/11758909/c0293aa0-a036-11e5-9dc9-fedaf55a1329.png)

**Comment by vitraiden** [comment]
I noticed that this was fixed already in IERecipes.java.  My apologies.

**Comment by BluSunrize** [comment]
Yeah this was literally fixed today, because I'm a derp =P

**Comment by Voxel-Friend** [comment]
Sorry for Commenting on a closed issue, but was 0.6.4 reuploaded with this fix? Im on 0.6.4 and I still have this issue...

**Comment by BluSunrize** [comment]
No it wasn't. this fix is for 0.6.5 onwards. I don't do reuploads, that only causes confusion

**Comment by Dreminon** [comment]
when will 0.6.5 be uploaded than? and thanks love your mod

**Comment by BluSunrize** [comment]
When it's done.
